### ISSUE TITLE
Interest in potentially reading ruby version from Gemfile.lock?

### ISSUE THREAD

**Issue by colinxfleming** [civisanalytics/ruby_audit#10]
hey! We were doing some chatting over in coinbase/salus about adding ruby_audit, so that the comprehensive security scanner could do its magic. I took a stab at it but ran into a wall around [here](https://github.com/civisanalytics/ruby_audit/blob/master/lib/ruby_audit/scanner.rb#L42), since it looks like there isn't a way to get ruby version from anything other than the active environment.

Would you have any interest in adding an option in ruby_audit to read ruby version from Gemfile.lock rather than environment? I'm more than happy to do the programming, just wanted to check first.

(Thanks much for this library! Have used it for years, it's great.)

**Comment by mikesaelim** [comment]
Hey @colinxfleming, sorry for the long wait.  Can you elaborate on the use case for scanning ruby and rubygems versions that aren't in the current environment?

**Comment by skomanduri** [comment]
I found an explanation of the issue here: https://github.com/coinbase/salus/issues/56#issuecomment-500166361

> Since this runs within the context of a docker container, I think that means it'll really be scanning the docker container for ruby and rubygems vulns rather than the lockfile, making it sorta useless.

In a docker container, we don't have access to anything but the filesystem. 
 https://github.com/coinbase/salus seems to be built with this assumption.

Unfortunately, `Gemfile.lock` doesn't store the Rubygems version, and only stores the Ruby version if it is specified in `Gemfile`.  I'm not sure how to get this information reliably from within a container.

**Comment by colinxfleming** [comment]
hi, sorry for taking so long to come back to this. thanks @skomanduri for topping it - that's pretty much the use case.

I did some experimentation and found that doing this reliably would probably require a bundler change. I doubt this issue will get a lot of traction bundler-side, so we can close this down if you'd like to keep the issues list clean.

**Comment by mikesaelim** [comment]
It's no problem.  I'll close the issue, but if a reliable way to do this appears, feel free to reopen this or open another issue!
